### ISSUE TITLE
Wrong returning datatype for prices causes malformed responses

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/woocommerce-payments#2827]
_I'm not 100% sure if we should consider this a bug so I open the question: WooCommerce payments seems to be doing things differently than WooCommerce core regarding price datatypes, hence causing problems when we use these assumptions elsewhere (like in the WooCommerce app, or extensions like Auctions for WooCommerce )._

### Description 

Some merchants have reported issue syncing their product lists when using the WooCommerce app. Looking through their error logs it seemed that some  plugin was altering the return type of product price to numeric values instead of string as we're expecting the values to be (for both the core WooCommerce plugin and the app). This causes parsing failure and hence the syncing failure.

After further debugging we discovered that this was actually WooCommerce Payments. From what I gather is altering the product meta and saving/updating it as Integer rather than String. Some example errors when the JSON decoder attempts to fetch the object:

```
2021/08/05 17:05:26:053  ⛔️ Error loading ProductVariation & Product for siteID: 191752495 productID:27454 variationID:27459 error:AnyError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)))
```

Related issues:
https://github.com/woocommerce/woocommerce-ios/pull/3679
https://github.com/woocommerce/woocommerce-ios/pull/4901
https://github.com/woocommerce/woocommerce-ios/issues/4737

Other cases where the plugin alters the product meta and expects a String as returning value, but fails due to the different returning datatype:

https://github.com/woocommerce/woocommerce-ios/issues/2822
https://github.com/woocommerce/woocommerce-ios/issues/3511

Note how the price becomes a double with ~20 decimals in this user site, rather than returning a formatted string :

![](https://user-images.githubusercontent.com/3812076/128492296-93780e4b-4ee2-4541-a8fd-0eee110fe2e1.png)

**Comment by thabotswana** [comment]
This seems to be related: 4269667-zen

`2021/09/02 22:47:47:464  ⛔️ Error updating Product: unknown(error: Yosemite.AnyError(error: Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "regular_price", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))))`

**Comment by anant1811** [comment]
Also reported in forum: https://wordpress.org/support/topic/changing-the-default-get_price-method-type-for-woocommerce/

**Comment by thabotswana** [comment]
Another report here: 4284917-zen

>we often have issues loading our products onto the app. A colleague has used her android phone and can successfully see all product images but iPhone users seem to have issues saying ‘unable to load feed’

**Comment by koke** [comment]
Another report here: 4301986-zen

> Hi, we are unable to view our products, variations, or update inventory from the app. It says unable to refresh. We have tried everything.

> Woo app is not functioning property. Can’t update inventory or view. Keep getting an “error” message. Even our web designer who has his app connected to a different store is receiving the same message. Please advise. We update inventory daily from the app as your site is too difficult for the quantity we do.

**Comment by designsimply** [comment]
@iamgabrielma or @thabotswana this may have been fixed by https://github.com/woocommerce/woocommerce-ios/pull/4901 and available for users in version 7.5 which is being rolled out this week—would it be possible for one of you to check in with the users mentioned on this issue to see if updating to 7.5 resolves the problem for them? If upgrading to 7.5 doesn't solve the problem, could you add a note to each ticket with a list of active plugins? Hopefully, comparing a list of active plugins will help us narrow down the source of the problem and if it doesn't then it should help us to know it may be more widespread.

<sup>(also see internal reference: p1632159118387200-slack-C6H8C3G23)</sup>

**Comment by iamgabrielma** [comment]
> @iamgabrielma or @thabotswana this may have been fixed by [woocommerce/woocommerce-ios#4901](https://github.com/woocommerce/woocommerce-ios/pull/4901) and available for users in version 7.5 which is being rolled out this week—would it be possible for one of you to check in with the users mentioned on this issue to see if updating to 7.5 resolves the problem for them? If upgrading to 7.5 doesn't solve the problem, could you add a note to each ticket with a list of active plugins? Hopefully, comparing a list of active plugins will help us narrow down the source of the problem and if it doesn't then it should help us to know it may be more widespread.
> 
> (also see internal reference: p1632159118387200-slack-C6H8C3G23)

Thanks for the heads up! We tested https://github.com/woocommerce/woocommerce-ios/pull/4901 and this indeed seems to fix the problem when the source is a variable product. However, the core issue remains which seems to be that  WooCommerce Payments does not apply the default WooCommerce Formatter - that transforms values to an output String - , and causes malformed responses, so the problem will keep happening for other cases where there are non-variable products. 

This most likely means that new bandaids will have to be applied in the future for different post-types or setups when WooCommerce Payments is active, or will not work well with the app.

We'll keep an eye on the reported cases and any new ones that may arise!

**Comment by iamgabrielma** [comment]
Adding another case from @hichamboushaba at p1632159118387200-slack-mobile-woo :

> I'm playing with WooCommerce's API in a small fun project, and today I noticed that the JSON deserialization was failing.
I went to my store to see what changed, and I noticed that WCPay has been updated to the version 3.0, and that the price of products is returned now as a number instead of string as it was before:
```
    "price": 18,
    "regular_price": "",
    "sale_price": "",
```
vs
```
    "price": "18",
    "regular_price": "",
    "sale_price": "",
```

> I confirmed that WCPay is causing this by deactivating the plugin. This doesn't affect WCAndroid since we use GSon, and it's lenient by default, so it doesn't enforce the field types, and I assume we are doing something similar in iOS, since no one complained about this, but still, a plugin changing the json like this seems weird, and would've broke the app completely if we were using a more strict json deserializing library (like my fun project)

**Comment by htdat** [comment]
It seems this issue comes from these hooks in MultiCurrecy feature. 
https://github.com/Automattic/woocommerce-payments/blob/21da7cd146ea5e294b79c6b8194a7ac40323500a/includes/multi-currency/FrontendPrices.php#L44-L51

Disabling these hooks seems to help. Also, casting string type here may help: 
https://github.com/Automattic/woocommerce-payments/blob/21da7cd146ea5e294b79c6b8194a7ac40323500a/includes/multi-currency/FrontendPrices.php#L84-L84

@Automattic/sigma could you have a look?
